# Generated by Django 4.0.1 on 2022-08-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/on_image.png', null=True, upload_to=''),
        ),
    ]
