export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_DETAILS_UPDATE_REQUEST = 'USER_DETAILS_UPDATE_REQUEST'
export const USER_DETAILS_UPDATE_SUCCESS = 'USER_DETAILS_UPDATE_SUCCESS'
export const USER_DETAILS_UPDATE_FAIL = 'USER_DETAILS_UPDATE_FAIL'
export const USER_DETAILS_UPDATE_RESET = 'USER_DETAILS_UPDATE_RESET'


// admin 

export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL'
export const USERS_LIST_RESET = 'USERS_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL'
export const GET_USER_DETAILS_RESET = 'GET_USER_DETAILS_RESET'

export const GET_USER_DETAILS_UPDATE_REQUEST = 'GET_USER_DETAILS_UPDATE_REQUEST'
export const GET_USER_DETAILS_UPDATE_SUCCESS = 'GET_USER_DETAILS_UPDATE_SUCCESS'
export const GET_USER_DETAILS_UPDATE_FAIL = 'GET_USER_DETAILS_UPDATE_FAIL'
export const GET_USER_DETAILS_UPDATE_RESET = 'GET_USER_DETAILS_UPDATE_RESET'

